name: Python Pytest

on: [push]

jobs:
  build-and-test:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install xmllint
        run: sudo apt-get install -y libxml2-utils

      # ~~~~~~~~~~~~~ Python setup ~~~~~~~~~~~~~
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install Python dependencies
        run: pip install -r requirements.txt

        # ~~~~~~~~~~~~~ Run ~~~~~~~~~~~~~
      - name: Run and compute coverage
        run: |
          ./get_coverage_for_challenge.sh TST
          grep "50" ./coverage.tdl
